Ajout Abdeel
leny/becode-js-corrections pull request #14
Opened 2019-06-24 14:38 UTC by abood1991

2019-06-24 17:02 UTC, leny requested changes

2019-06-24 17:02 UTC, leny commented on 07-classes/03-inheritance/script.js
> +    }
Peux-tu retirer `this.constructor.greeting = "Meow";`, et, en-dehors de la class, ajouter `Cat.greeting = "Meow"` ?

2019-06-24 17:02 UTC, leny commented on 07-classes/03-inheritance/script.js
> +            this.constructor.greeting = "woof";
Peux-tu ensuite faire la même chose ici ?

Merci!

2019-06-25 07:23 UTC, abood1991 commented on 07-classes/03-inheritance/script.js
> +            this.constructor.greeting = "woof";
Fait

2019-06-25 08:52 UTC, leny approved these changes
Super, un grand merci!

2019-06-25 08:52 UTC, merged